#! /usr/bin/env ruby

require 'optparse'
require 'stringio'

class Format
  def self.build(template_string)
    self.new(template_string)
  end

  def initialize(template_string)
    remain = template_string
    @sseq = []
    while m = remain.match(/^(.*?)\{(.+?)\}(.*)$/)
      @sseq.push(m[1])
      capture = m[2].match?(/\d+/) ? m[2].to_i : m[2]
      @sseq.push(Placeholder.new(capture: capture))
      remain = m[3]
    end
    @sseq.push(remain)
  end

  def render(params)
    @sseq.map do |s|
      case s
      when String
        s
      when Placeholder
        params[s.capture]
      else
        raise "Unexpected object: #{s.inspect}"
      end
    end.join('')
  end

  class Placeholder < Struct.new(:capture, keyword_init: true); end
end

class Scanner
  attr_accessor :matcher, :output_format

  def self.build(args: ARGV, format_builder: Format)
    regex = nil
    delimiter = nil
    parser = OptionParser.new do |opts|
      opts.on('-p [PATTERN]', 'specify regexp') do |passed_regex|
        regex = passed_regex
      end
      opts.on('-d [DELIMITER]', 'specify delimiter') do |passed_delimiter|
        delimiter = passed_delimiter
      end
    end

    output_format = format_builder.build(parser.parse(args).join(' '))
    matcher = if regex
                RegexpMatcher.new(regexp: regex)
              elsif delimiter
                DelimiterMatcher.new(delimiter: delimiter)
              else
                DelimiterMatcher.new(delimiter: '\s+')
              end

    Scanner.new(matcher: matcher, output_format: output_format)
  end

  def initialize(matcher:, output_format:)
    self.matcher = matcher
    self.output_format = output_format
  end

  def scan(reader: $stdin, writer: $stdout)
    output = StringIO.new
    reader
      .readlines(chomp: true)
      .each do |line|
          matched_data = matcher.match(line)
          next unless matched_data
          text = output_format.render(matched_data)
          output.puts(text)
        end
    writer.puts(output.string)
  end
end

class DelimiterMatcher
  def initialize(delimiter:)
    @delimiter_regex = Regexp.compile delimiter
  end

  def match(line)
    format_params = {}
    [line, *line.split(@delimiter_regex)].each.with_index do |capture, index|
      format_params[index] = capture
    end
    format_params
  end
end

class RegexpMatcher
  def initialize(regexp:)
    @regexp = Regexp.compile regexp
  end

  def match(line)
    @regexp.match(line)
  end
end

if __FILE__ == $0
  require 'stackprof'

  StackProf.run(mode: :cpu, raw: true, out: 'tmp/stackprof-cpu-myapp.dump', interval: 100) do
    Scanner.build.scan
  end
end
